version: '3.8'

services:
  # db service
  bookstack_db:
    image: mysql:8.0-debian
    container_name: case5-db
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia_asdos
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password_wiki
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - wiki-network
    restart: unless-stopped
    # memastikan db siap sebelum app dijalankan
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # app service
  bookstack_app:
    image: linuxserver/bookstack:latest
    container_name: case5-app
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:8085
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_USERNAME=bookstack
      - DB_PASS=password_wiki
      - DB_DATABASE=bookstack
      # key hasil generate
      - APP_KEY=base64:KEHuLjqzHiMTgVONg2vx5rNO75MVPxe92ZbEMKwSexA=
    volumes:
      - ./app_config:/config
    # app hanya akan jalan after database sehat krn app butuh db dulu biar bisa jalan
    depends_on:
      bookstack_db:
        condition: service_healthy
    networks:
      - wiki-network
    restart: unless-stopped

  # Web Server Proxy (Nginx)
  webserver:
    image: nginx:alpine
    container_name: case5-nginx
    ports:
      - "8085:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bookstack_app
    networks:
      - wiki-network
    restart: unless-stopped

  # Database Interface (PhpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: case5-pma
    environment:
      - PMA_HOST=bookstack_db
      - PMA_USER=root
      - PMA_PASSWORD=rahasia_asdos
    ports:
      - "8086:80"
    depends_on:
      - bookstack_db
    networks:
      - wiki-network

networks:
  wiki-network:
    driver: bridge